# Generated by Django 6.0.7 on 2026-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhar_number',
            field=models.CharField(max_length=30),
        ),
    ]
