# Generated by Django 6.0.7 on 2026-09-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_studentapplication_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='application_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('reporting_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card', to='exams.studentapplication')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admit_cards', to='exams.examcenter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
