# Generated by Django 6.0.7 on 2026-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentapplication_application_number_admitcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='exam_venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
