# Generated by Django 6.0.7 on 2026-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
    ]
