# Generated by Django 6.0.7 on 2026-08-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
